#!/usr/bin/env bash
# display fizz,buzz and fizzbuzz for mutiple of 3,5 and both respectively
i=1 
while ((i<=100))
do
if ((i%3==0 && i%5==0))
then 
echo "FizzBuzz"
elif ((i%3==0))
then
 echo "Fizz"
elif ((i%5==0))
then
echo "Buzz"
else
echo "$i"
fi
((i+=1))
done
