#!/usr/bin/env bash
# This script tells a story based on the /etc/passwd file
IFS=:
while read -r username password uid gid fullname homedir shell
do 
echo "The user $username is part of the $gid gang, lives in $homedir and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $fullname"
done < /etc/passwd

