#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes
# display hours from 0 to 12
# display minutes from 1 to 59
hrs=0
while ((hrs <13))
do 
	echo "Hours:$hrs"
	min=1
 while ((min <60))
 do
	 echo $min
	 ((min+=1))
 done
 ((hrs+=1))
done

